name: Append build number to version

inputs:
  package-path:
    description: Package path
    required: true
  package-version:
    description: Package version
    required: true

runs:
  using: composite
  steps:
    - name: Append build number to version
      env:
        PACKAGE_PATH: ${{ inputs.package-path }}
        PACKAGE_VERSION: ${{ inputs.package-version }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        OLD_VERSION=${PACKAGE_VERSION}
        NEW_VERSION=${OLD_VERSION}.post${RUN_NUMBER}
        sed -i "s/^__version__ = \\\"${OLD_VERSION}\\\"$/__version__ = \\\"${NEW_VERSION}\\\"/" "${PACKAGE_PATH}"
      shell: bash
