name: Publish to PyPI

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-publish:
    name: Build and publish distributions to PyPi
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Read metadata
      id: metadata
      uses: ./.github/actions/metadata

    - name: Set up Python ${{ steps.metadata.outputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ steps.metadata.outputs.python-version }}

    - name: Install build dependencies
      run: python -m pip install build --user

    - name: Build distributions
      run: python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
